/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pers_xjh_note_model_bean_JNITest */

#ifndef _Included_pers_xjh_note_model_bean_JNITest
#define _Included_pers_xjh_note_model_bean_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pers_xjh_note_model_bean_JNITest
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_pers_xjh_note_model_bean_JNITest_sayHello
  (JNIEnv *env, jclass) {
        return env->NewStringUTF("Hello from C++");
  }

#ifdef __cplusplus
}
#endif
#endif